# This is the configuration file for the netlify preview deploys
# See https://www.netlify.com/docs/netlify-toml-reference/ for more

[[redirects]]
  from = "/"
  to = "/__tests__/integration/mirador/"
